# Generated by Django 5.1 on 2024-09-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_train_destination_station_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('SL', 'Sleeper'), ('GN', 'General'), ('LG', 'Luggage'), ('PT', 'Pantry'), ('GEN', 'Generator'), ('AC3', 'AirConditioner 3'), ('AC2', 'AirConditioner 2'), ('H', 'FIRSTCLASS')], max_length=5)),
                ('generation', models.CharField(choices=[('VB', 'Vande Bharat'), ('LHB', 'LHB'), ('ICF', 'ICF'), ('DD', 'Double Decker')], max_length=5)),
                ('number_of_seats', models.PositiveSmallIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
