# Generated by Django 5.1 on 2024-09-07 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_traincoaches_delete_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='traincoaches',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traincoaches',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_coaches', to='core.train'),
        ),
        migrations.AlterField(
            model_name='traincoaches',
            name='type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('GN', 'General'), ('LG', 'Luggage'), ('PT', 'Pantry'), ('GEN', 'Generator'), ('AC3', 'AirConditioner 3'), ('AC2', 'AirConditioner 2'), ('H', 'FIRSTCLASS'), ('CC', 'Chair Car'), ('EC', 'Executive Class')], max_length=5),
        ),
    ]
