# Generated by Django 5.1 on 2024-09-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coachconfiguration_alter_train_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachConfiguration',
        ),
    ]
