# Generated by Django 5.1 on 2024-09-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_coachconfiguration'),
        ('station', '0004_alter_station_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainHalts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_halt', models.BooleanField(default=True)),
                ('halts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_halts', to='station.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_halts', to='core.train')),
            ],
        ),
    ]
