# Generated by Django 5.1 on 2024-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trainhalts'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='express_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
