# Generated by Django 5.1 on 2024-09-16 17:17

import django.db.models.deletion
import trip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_train_express_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSeatAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField()),
                ('date', models.DateField(validators=[trip.models.validated_date])),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_seats_available', to='core.train')),
            ],
        ),
    ]
