# Generated by Django 5.1 on 2024-09-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
                ('number_of_platforms', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('LD', 'Lakshadweep'), ('DL', 'Delhi'), ('PY', 'Puducherry'), ('LA', 'Ladakh'), ('JK', 'Jammu and Kashmir')], max_length=2)),
                ('zone', models.CharField(choices=[('CR', 'Central Railway'), ('ECR', 'East Central Railway'), ('ECoR', 'East Coast Railway'), ('ER', 'Eastern Railway'), ('NCR', 'North Central Railway'), ('NFR', 'Northeast Frontier Railway'), ('NER', 'North Eastern Railway'), ('NWR', 'North Western Railway'), ('SCR', 'South Central Railway'), ('SCoR', 'South Coast Railway'), ('SECR', 'South East Central Railway'), ('SER', 'South Eastern Railway'), ('SR', 'Southern Railway'), ('SWR', 'South Western Railway'), ('WCR', 'West Central Railway'), ('WR', 'Western Railway'), ('MRK', 'Metro Railway, Kolkata')], max_length=5)),
            ],
        ),
    ]
