# Generated by Django 5.1 on 2024-09-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_stations', models.ManyToManyField(related_name='down_stations', to='station.station')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
                ('up_stations', models.ManyToManyField(related_name='up_stations', to='station.station')),
            ],
        ),
    ]
