# Generated by Django 5.1 on 2024-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_stationroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationroute',
            name='down_stations',
        ),
        migrations.RemoveField(
            model_name='stationroute',
            name='up_stations',
        ),
        migrations.AddField(
            model_name='stationroute',
            name='routes',
            field=models.ManyToManyField(related_name='routes', to='station.station'),
        ),
    ]
