# Generated by Django 5.1 on 2024-09-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_remove_stationroute_down_stations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['code']},
        ),
    ]
