from django.db import models

class IndianState(models.TextChoices):
    ANDHRA_PRADESH = 'AP', 'Andhra Pradesh'
    ARUNACHAL_PRADESH = 'AR', 'Arunachal Pradesh'
    ASSAM = 'AS', 'Assam'
    BIHAR = 'BR', 'Bihar'
    CHHATTISGARH = 'CG', 'Chhattisgarh'
    GOA = 'GA', 'Goa'
    GUJARAT = 'GJ', 'Gujarat'
    HARYANA = 'HR', 'Haryana'
    HIMACHAL_PRADESH = 'HP', 'Himachal Pradesh'
    JHARKHAND = 'JH', 'Jharkhand'
    KARNATAKA = 'KA', 'Karnataka'
    KERALA = 'KL', 'Kerala'
    MADHYA_PRADESH = 'MP', 'Madhya Pradesh'
    MAHARASHTRA = 'MH', 'Maharashtra'
    MANIPUR = 'MN', 'Manipur'
    MEGHALAYA = 'ML', 'Meghalaya'
    MIZORAM = 'MZ', 'Mizoram'
    NAGALAND = 'NL', 'Nagaland'
    ODISHA = 'OR', 'Odisha'
    PUNJAB = 'PB', 'Punjab'
    RAJASTHAN = 'RJ', 'Rajasthan'
    SIKKIM = 'SK', 'Sikkim'
    TAMIL_NADU = 'TN', 'Tamil Nadu'
    TELANGANA = 'TG', 'Telangana'
    TRIPURA = 'TR', 'Tripura'
    UTTAR_PRADESH = 'UP', 'Uttar Pradesh'
    UTTARAKHAND = 'UK', 'Uttarakhand'
    WEST_BENGAL = 'WB', 'West Bengal'
    ANDAMAN_NICOBAR = 'AN', 'Andaman and Nicobar Islands'
    CHANDIGARH = 'CH', 'Chandigarh'
    DADRA_NAGAR_HAVELI = 'DN', 'Dadra and Nagar Haveli'
    DAMAN_DIU = 'DD', 'Daman and Diu'
    LAKSHADWEEP = 'LD', 'Lakshadweep'
    DELHI = 'DL', 'Delhi'
    PUDUCHERRY = 'PY', 'Puducherry'
    LADAKH = 'LA', 'Ladakh'
    JAMMU_KASHMIR = 'JK', 'Jammu and Kashmir'


class IndianRailwayZone(models.TextChoices):
    CENTRAL_RAILWAY = 'CR', 'Central Railway'
    EAST_CENTRAL_RAILWAY = 'ECR', 'East Central Railway'
    EAST_COAST_RAILWAY = 'ECoR', 'East Coast Railway'
    EASTERN_RAILWAY = 'ER', 'Eastern Railway'
    NORTH_CENTRAL_RAILWAY = 'NCR', 'North Central Railway'
    NORTH_EAST_FRONTIER_RAILWAY = 'NFR', 'Northeast Frontier Railway'
    NORTH_EASTERN_RAILWAY = 'NER', 'North Eastern Railway'
    NORTH_WESTERN_RAILWAY = 'NWR', 'North Western Railway'
    SOUTH_CENTRAL_RAILWAY = 'SCR', 'South Central Railway'
    SOUTH_COAST_RAILWAY = 'SCoR', 'South Coast Railway'
    SOUTH_EAST_CENTRAL_RAILWAY = 'SECR', 'South East Central Railway'
    SOUTH_EASTERN_RAILWAY = 'SER', 'South Eastern Railway'
    SOUTHERN_RAILWAY = 'SR', 'Southern Railway'
    SOUTH_WESTERN_RAILWAY = 'SWR', 'South Western Railway'
    WEST_CENTRAL_RAILWAY = 'WCR', 'West Central Railway'
    WESTERN_RAILWAY = 'WR', 'Western Railway'
    METRO_RAILWAY_KOLKATA = 'MRK', 'Metro Railway, Kolkata'


class StationTypeChoice(models.TextChoices):
    CENTRAL = 'CT', 'Central'
    JUNCTION = 'JT', 'Junction'
    Terminus = 'TM', 'Terminus'
    NORMAL = 'NR', 'Normal'